version: '3.8'

services:
  backend:
    container_name: social_app_backend
    build:
      context: .
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo
    container_name: social_app_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: