version: '3.8'

services:
  backend:
    build:
      target: production
    ports:
      - "3000:3000"
    command: npm run start
    restart: always

  mongodb:
    ports:
      - "27017:27017"
    restart: always